/* Generated by a program written by John Boyland */
#include <stdio.h>
#include "aps-tree.h"
void dump_lisp_Signature(Signature);
void dump_lisp_Type(Type);
void dump_lisp_Expression(Expression);
void dump_lisp_Pattern(Pattern);
void dump_lisp_SignatureDecl(SignatureDecl);
void dump_lisp_TypeDecl(TypeDecl);
void dump_lisp_ValueDecl(ValueDecl);
void dump_lisp_PatternDecl(PatternDecl);
void dump_lisp_Program(Program);
void dump_lisp_Unit(Unit);
void dump_lisp_Declaration(Declaration);
void dump_lisp_Renaming(Renaming);
void dump_lisp_Match(Match);
void dump_lisp_Direction(Direction);
void dump_lisp_Default(Default);
void dump_lisp_Units(Units);
void dump_lisp_Declarations(Declarations);
void dump_lisp_Matches(Matches);
void dump_lisp_Renamings(Renamings);
void dump_lisp_Signatures(Signatures);
void dump_lisp_Types(Types);
void dump_lisp_Expressions(Expressions);
void dump_lisp_Patterns(Patterns);
void dump_lisp_Formals(Formals);
void dump_lisp_TypeFormals(TypeFormals);
void dump_lisp_Actuals(Actuals);
void dump_lisp_TypeActuals(TypeActuals);
void dump_lisp_PatternActuals(PatternActuals);

void dump_lisp_Signature(Signature _node){
  switch (Signature_KEY(_node)) {
    default: fatal_error("dump_lisp_Signature crashes");
    case KEYsig_name:
      printf("%c(sig_name",10);
dump_lisp_Symbol(sig_name_name(_node));
      printf(")");
      break;
    case KEYno_sig:
      printf("%c(no_sig",10);
      printf(")");
      break;
    case KEYsig_inst:
      printf("%c(sig_inst",10);
dump_lisp_Signature(sig_inst_sig(_node));
dump_lisp_TypeActuals(sig_inst_actuals(_node));
      printf(")");
      break;
    case KEYqual_sig:
      printf("%c(qual_sig",10);
dump_lisp_Type(qual_sig_inst(_node));
dump_lisp_Signature(qual_sig_sig(_node));
      printf(")");
      break;
    case KEYvar_sig:
      printf("%c(var_sig",10);
dump_lisp_Signature(var_sig_sig(_node));
      printf(")");
      break;
    case KEYconstant_sig:
      printf("%c(constant_sig",10);
dump_lisp_Signature(constant_sig_sig(_node));
      printf(")");
      break;
    case KEYmodule_sig:
      printf("%c(module_sig",10);
dump_lisp_TypeFormals(module_sig_type_formals(_node));
dump_lisp_Formals(module_sig_formals(_node));
dump_lisp_Declaration(module_sig_return_type(_node));
      printf(")");
      break;
    case KEYfixed_sig:
      printf("%c(fixed_sig",10);
dump_lisp_Types(fixed_sig_types(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Type(Type _node){
  switch (Type_KEY(_node)) {
    default: fatal_error("dump_lisp_Type crashes");
    case KEYtype_name:
      printf("%c(type_name",10);
dump_lisp_Symbol(type_name_name(_node));
      printf(")");
      break;
    case KEYno_type:
      printf("%c(no_type",10);
      printf(")");
      break;
    case KEYtype_inst:
      printf("%c(type_inst",10);
dump_lisp_Type(type_inst_base(_node));
dump_lisp_TypeActuals(type_inst_type_actuals(_node));
dump_lisp_Actuals(type_inst_actuals(_node));
      printf(")");
      break;
    case KEYqual_type:
      printf("%c(qual_type",10);
dump_lisp_Type(qual_type_inst(_node));
dump_lisp_Type(qual_type_type_(_node));
      printf(")");
      break;
    case KEYremote_type:
      printf("%c(remote_type",10);
dump_lisp_Type(remote_type_nodetype(_node));
      printf(")");
      break;
    case KEYordered_set_type:
      printf("%c(ordered_set_type",10);
dump_lisp_Type(ordered_set_type_u(_node));
dump_lisp_Expression(ordered_set_type_equal(_node));
dump_lisp_Expression(ordered_set_type_order(_node));
      printf(")");
      break;
    case KEYset_type:
      printf("%c(set_type",10);
dump_lisp_Type(set_type_u(_node));
dump_lisp_Expression(set_type_equal(_node));
      printf(")");
      break;
    case KEYlist_type:
      printf("%c(list_type",10);
dump_lisp_Type(list_type_u(_node));
      printf(")");
      break;
    case KEYfunction_type:
      printf("%c(function_type",10);
dump_lisp_Formals(function_type_formals(_node));
dump_lisp_Declaration(function_type_return_value(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Expression(Expression _node){
  switch (Expression_KEY(_node)) {
    default: fatal_error("dump_lisp_Expression crashes");
    case KEYvalue_name:
      printf("%c(value_name",10);
dump_lisp_Symbol(value_name_name(_node));
      printf(")");
      break;
    case KEYvalue_inst:
      printf("%c(value_inst",10);
dump_lisp_Expression(value_inst_base(_node));
dump_lisp_TypeActuals(value_inst_actuals(_node));
      printf(")");
      break;
    case KEYqual_value:
      printf("%c(qual_value",10);
dump_lisp_Type(qual_value_inst(_node));
dump_lisp_Expression(qual_value_value(_node));
      printf(")");
      break;
    case KEYinteger_const:
      printf("%c(integer_const",10);
dump_lisp_String(integer_const_token(_node));
      printf(")");
      break;
    case KEYstring_const:
      printf("%c(string_const",10);
dump_lisp_String(string_const_token(_node));
      printf(")");
      break;
    case KEYchar_const:
      printf("%c(char_const",10);
dump_lisp_String(char_const_token(_node));
      printf(")");
      break;
    case KEYundefined:
      printf("%c(undefined",10);
      printf(")");
      break;
    case KEYno_expr:
      printf("%c(no_expr",10);
      printf(")");
      break;
    case KEYfuncall:
      printf("%c(funcall",10);
dump_lisp_Expression(funcall_f(_node));
dump_lisp_Actuals(funcall_actuals(_node));
      printf(")");
      break;
    case KEYreduce:
      printf("%c(reduce",10);
dump_lisp_Expression(reduce_f(_node));
dump_lisp_Expressions(reduce_elems(_node));
      printf(")");
      break;
    case KEYsequence:
      printf("%c(sequence",10);
dump_lisp_Expressions(sequence_elems(_node));
dump_lisp_Type(sequence_type_(_node));
      printf(")");
      break;
    case KEYconstructor_key:
      printf("%c(constructor_key",10);
dump_lisp_Expression(constructor_key_name(_node));
      printf(")");
      break;
    case KEYsignature_value:
      printf("%c(signature_value",10);
dump_lisp_Signature(signature_value_s(_node));
      printf(")");
      break;
    case KEYtype_value:
      printf("%c(type_value",10);
dump_lisp_Type(type_value_t(_node));
      printf(")");
      break;
    case KEYpattern_value:
      printf("%c(pattern_value",10);
dump_lisp_Pattern(pattern_value_p(_node));
      printf(")");
      break;
    case KEYrepeat:
      printf("%c(repeat",10);
dump_lisp_Expression(repeat_expr(_node));
      printf(")");
      break;
    case KEYguarded:
      printf("%c(guarded",10);
dump_lisp_Expression(guarded_expr(_node));
dump_lisp_Expression(guarded_cond(_node));
      printf(")");
      break;
    case KEYcontrolled:
      printf("%c(controlled",10);
dump_lisp_Expression(controlled_expr(_node));
dump_lisp_ValueDecl(controlled_decl(_node));
dump_lisp_Expression(controlled_set(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Pattern(Pattern _node){
  switch (Pattern_KEY(_node)) {
    default: fatal_error("dump_lisp_Pattern crashes");
    case KEYpattern_name:
      printf("%c(pattern_name",10);
dump_lisp_Symbol(pattern_name_name(_node));
      printf(")");
      break;
    case KEYno_pattern:
      printf("%c(no_pattern",10);
      printf(")");
      break;
    case KEYpattern_inst:
      printf("%c(pattern_inst",10);
dump_lisp_Pattern(pattern_inst_base(_node));
dump_lisp_TypeActuals(pattern_inst_actuals(_node));
      printf(")");
      break;
    case KEYqual_pattern:
      printf("%c(qual_pattern",10);
dump_lisp_Type(qual_pattern_inst(_node));
dump_lisp_Pattern(qual_pattern_pattern(_node));
      printf(")");
      break;
    case KEYsimple_pattern:
      printf("%c(simple_pattern",10);
dump_lisp_Pattern(simple_pattern_con(_node));
dump_lisp_PatternActuals(simple_pattern_actuals(_node));
      printf(")");
      break;
    case KEYpattern_actual:
      printf("%c(pattern_actual",10);
dump_lisp_Pattern(pattern_actual_arg(_node));
dump_lisp_Expression(pattern_actual_formal(_node));
      printf(")");
      break;
    case KEYsequence_pattern:
      printf("%c(sequence_pattern",10);
dump_lisp_Patterns(sequence_pattern_actuals(_node));
dump_lisp_Type(sequence_pattern_type_(_node));
      printf(")");
      break;
    case KEYrest_pattern:
      printf("%c(rest_pattern",10);
dump_lisp_Pattern(rest_pattern_constraint(_node));
      printf(")");
      break;
    case KEYchoice_pattern:
      printf("%c(choice_pattern",10);
dump_lisp_Patterns(choice_pattern_choices(_node));
      printf(")");
      break;
    case KEYand_pattern:
      printf("%c(and_pattern",10);
dump_lisp_Pattern(and_pattern_p1(_node));
dump_lisp_Pattern(and_pattern_p2(_node));
      printf(")");
      break;
    case KEYpattern_var:
      printf("%c(pattern_var",10);
dump_lisp_ValueDecl(pattern_var_as_value(_node));
      printf(")");
      break;
    case KEYcondition:
      printf("%c(condition",10);
dump_lisp_Expression(condition_e(_node));
      printf(")");
      break;
  }
}

void dump_lisp_SignatureDecl(SignatureDecl _node){
  switch (SignatureDecl_KEY(_node)) {
    default: fatal_error("dump_lisp_SignatureDecl crashes");
    case KEYa_signature:
      printf("%c(a_signature",10);
dump_lisp_Symbol(a_signature_name(_node));
dump_lisp_TypeFormals(a_signature_type_formals(_node));
dump_lisp_Boolean(a_signature_constant_(_node));
dump_lisp_Boolean(a_signature_exported(_node));
      printf(")");
      break;
  }
}

void dump_lisp_TypeDecl(TypeDecl _node){
  switch (TypeDecl_KEY(_node)) {
    default: fatal_error("dump_lisp_TypeDecl crashes");
    case KEYa_type:
      printf("%c(a_type",10);
dump_lisp_Symbol(a_type_name(_node));
dump_lisp_TypeFormals(a_type_type_formals(_node));
dump_lisp_Signatures(a_type_signatures(_node));
dump_lisp_Boolean(a_type_constant_(_node));
dump_lisp_Boolean(a_type_exported(_node));
      printf(")");
      break;
  }
}

void dump_lisp_ValueDecl(ValueDecl _node){
  switch (ValueDecl_KEY(_node)) {
    default: fatal_error("dump_lisp_ValueDecl crashes");
    case KEYa_value:
      printf("%c(a_value",10);
dump_lisp_Symbol(a_value_name(_node));
dump_lisp_TypeFormals(a_value_type_formals(_node));
dump_lisp_Type(a_value_type_(_node));
dump_lisp_Boolean(a_value_constant_(_node));
dump_lisp_Boolean(a_value_exported(_node));
      printf(")");
      break;
  }
}

void dump_lisp_PatternDecl(PatternDecl _node){
  switch (PatternDecl_KEY(_node)) {
    default: fatal_error("dump_lisp_PatternDecl crashes");
    case KEYa_pattern:
      printf("%c(a_pattern",10);
dump_lisp_Symbol(a_pattern_name(_node));
dump_lisp_TypeFormals(a_pattern_type_formals(_node));
dump_lisp_Type(a_pattern_type_(_node));
dump_lisp_Boolean(a_pattern_constant_(_node));
dump_lisp_Boolean(a_pattern_exported(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Program(Program _node){
  switch (Program_KEY(_node)) {
    default: fatal_error("dump_lisp_Program crashes");
    case KEYprogram:
      printf("%c(program",10);
dump_lisp_Units(program_units(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Unit(Unit _node){
  switch (Unit_KEY(_node)) {
    default: fatal_error("dump_lisp_Unit crashes");
    case KEYno_unit:
      printf("%c(no_unit",10);
      printf(")");
      break;
    case KEYwith_unit:
      printf("%c(with_unit",10);
dump_lisp_String(with_unit_name(_node));
      printf(")");
      break;
    case KEYdecl_unit:
      printf("%c(decl_unit",10);
dump_lisp_Declaration(decl_unit_decl(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Declaration(Declaration _node){
  switch (Declaration_KEY(_node)) {
    default: fatal_error("dump_lisp_Declaration crashes");
    case KEYno_decl:
      printf("%c(no_decl",10);
      printf(")");
      break;
    case KEYmodule_decl:
      printf("%c(module_decl",10);
dump_lisp_SignatureDecl(module_decl_as_sig(_node));
dump_lisp_TypeDecl(module_decl_as_tfunc(_node));
dump_lisp_Declarations(module_decl_contents(_node));
      printf(")");
      break;
    case KEYsignature_decl:
      printf("%c(signature_decl",10);
dump_lisp_SignatureDecl(signature_decl_as_sig(_node));
dump_lisp_Declaration(signature_decl_creating(_node));
dump_lisp_Declarations(signature_decl_contents(_node));
      printf(")");
      break;
    case KEYphylum_decl:
      printf("%c(phylum_decl",10);
dump_lisp_TypeDecl(phylum_decl_as_type(_node));
dump_lisp_Type(phylum_decl_type_(_node));
      printf(")");
      break;
    case KEYconstructor_decl:
      printf("%c(constructor_decl",10);
dump_lisp_ValueDecl(constructor_decl_as_value(_node));
dump_lisp_PatternDecl(constructor_decl_as_pattern(_node));
dump_lisp_Declaration(constructor_decl_body(_node));
      printf(")");
      break;
    case KEYattribute_decl:
      printf("%c(attribute_decl",10);
dump_lisp_ValueDecl(attribute_decl_as_value(_node));
dump_lisp_Direction(attribute_decl_direction(_node));
dump_lisp_Default(attribute_decl_default(_node));
      printf(")");
      break;
    case KEYtype_decl:
      printf("%c(type_decl",10);
dump_lisp_TypeDecl(type_decl_as_type(_node));
dump_lisp_Type(type_decl_type_(_node));
      printf(")");
      break;
    case KEYfunction_decl:
      printf("%c(function_decl",10);
dump_lisp_ValueDecl(function_decl_as_value(_node));
dump_lisp_Declaration(function_decl_body(_node));
      printf(")");
      break;
    case KEYprocedure_decl:
      printf("%c(procedure_decl",10);
dump_lisp_ValueDecl(procedure_decl_as_value(_node));
dump_lisp_Declaration(procedure_decl_body(_node));
      printf(")");
      break;
    case KEYtop_level_match:
      printf("%c(top_level_match",10);
dump_lisp_Match(top_level_match_m(_node));
      printf(")");
      break;
    case KEYvalue_decl:
      printf("%c(value_decl",10);
dump_lisp_ValueDecl(value_decl_as_value(_node));
dump_lisp_Direction(value_decl_direction(_node));
dump_lisp_Default(value_decl_default(_node));
      printf(")");
      break;
    case KEYpattern_decl:
      printf("%c(pattern_decl",10);
dump_lisp_PatternDecl(pattern_decl_as_pattern(_node));
dump_lisp_Pattern(pattern_decl_choices(_node));
      printf(")");
      break;
    case KEYinheritance:
      printf("%c(inheritance",10);
dump_lisp_Type(inheritance_used(_node));
dump_lisp_Renamings(inheritance_renamings(_node));
      printf(")");
      break;
    case KEYpragma_decl:
      printf("%c(pragma_decl",10);
dump_lisp_Symbol(pragma_decl_name(_node));
dump_lisp_Expressions(pragma_decl_parameters(_node));
      printf(")");
      break;
    case KEYstmts:
      printf("%c(stmts",10);
dump_lisp_Declarations(stmts_body(_node));
      printf(")");
      break;
    case KEYeffect:
      printf("%c(effect",10);
dump_lisp_Expression(effect_e(_node));
      printf(")");
      break;
    case KEYassign:
      printf("%c(assign",10);
dump_lisp_Expression(assign_lhs(_node));
dump_lisp_Expression(assign_rhs(_node));
      printf(")");
      break;
    case KEYif_stmt:
      printf("%c(if_stmt",10);
dump_lisp_Expression(if_stmt_cond(_node));
dump_lisp_Declaration(if_stmt_if_true(_node));
dump_lisp_Declaration(if_stmt_if_false(_node));
      printf(")");
      break;
    case KEYfor_in_stmt:
      printf("%c(for_in_stmt",10);
dump_lisp_ValueDecl(for_in_stmt_formal(_node));
dump_lisp_Expression(for_in_stmt_seq(_node));
dump_lisp_Declaration(for_in_stmt_body(_node));
      printf(")");
      break;
    case KEYfor_on_stmt:
      printf("%c(for_on_stmt",10);
dump_lisp_ValueDecl(for_on_stmt_formal(_node));
dump_lisp_Expression(for_on_stmt_seq(_node));
dump_lisp_Declaration(for_on_stmt_body(_node));
      printf(")");
      break;
    case KEYfor_stmt:
      printf("%c(for_stmt",10);
dump_lisp_Expression(for_stmt_expr(_node));
dump_lisp_Matches(for_stmt_matchers(_node));
      printf(")");
      break;
    case KEYcase_stmt:
      printf("%c(case_stmt",10);
dump_lisp_Expression(case_stmt_expr(_node));
dump_lisp_Matches(case_stmt_matchers(_node));
dump_lisp_Declaration(case_stmt_default(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Renaming(Renaming _node){
  switch (Renaming_KEY(_node)) {
    default: fatal_error("dump_lisp_Renaming crashes");
    case KEYno_renaming:
      printf("%c(no_renaming",10);
      printf(")");
      break;
    case KEYsignature_replacement:
      printf("%c(signature_replacement",10);
dump_lisp_Signature(signature_replacement_old(_node));
dump_lisp_Signature(signature_replacement_ew(_node));
      printf(")");
      break;
    case KEYtype_replacement:
      printf("%c(type_replacement",10);
dump_lisp_Type(type_replacement_old(_node));
dump_lisp_Type(type_replacement_new(_node));
      printf(")");
      break;
    case KEYvalue_replacement:
      printf("%c(value_replacement",10);
dump_lisp_Expression(value_replacement_old(_node));
dump_lisp_Expression(value_replacement_new(_node));
      printf(")");
      break;
    case KEYpattern_replacement:
      printf("%c(pattern_replacement",10);
dump_lisp_Pattern(pattern_replacement_old(_node));
dump_lisp_Pattern(pattern_replacement_new(_node));
      printf(")");
      break;
    case KEYsignature_renaming:
      printf("%c(signature_renaming",10);
dump_lisp_SignatureDecl(signature_renaming_decl(_node));
dump_lisp_Signature(signature_renaming_old(_node));
dump_lisp_Renamings(signature_renaming_elements(_node));
      printf(")");
      break;
    case KEYtype_renaming:
      printf("%c(type_renaming",10);
dump_lisp_TypeDecl(type_renaming_decl(_node));
dump_lisp_Type(type_renaming_old(_node));
      printf(")");
      break;
    case KEYvalue_renaming:
      printf("%c(value_renaming",10);
dump_lisp_ValueDecl(value_renaming_decl(_node));
dump_lisp_Expression(value_renaming_old(_node));
      printf(")");
      break;
    case KEYpattern_renaming:
      printf("%c(pattern_renaming",10);
dump_lisp_PatternDecl(pattern_renaming_decl(_node));
dump_lisp_Pattern(pattern_renaming_old(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Match(Match _node){
  switch (Match_KEY(_node)) {
    default: fatal_error("dump_lisp_Match crashes");
    case KEYmatcher:
      printf("%c(matcher",10);
dump_lisp_TypeFormals(matcher_polymorphism(_node));
dump_lisp_Pattern(matcher_pat(_node));
dump_lisp_Declaration(matcher_stmt(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Direction(Direction _node){
  switch (Direction_KEY(_node)) {
    default: fatal_error("dump_lisp_Direction crashes");
    case KEYno_direction:
      printf("%c(no_direction",10);
dump_lisp_Boolean(no_direction_is_input(_node));
      printf(")");
      break;
    case KEYcollection_:
      printf("%c(collection_",10);
dump_lisp_Boolean(collection__is_input(_node));
      printf(")");
      break;
    case KEYcircular_:
      printf("%c(circular_",10);
dump_lisp_Boolean(circular__is_input(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Default(Default _node){
  switch (Default_KEY(_node)) {
    default: fatal_error("dump_lisp_Default crashes");
    case KEYsimple:
      printf("%c(simple",10);
dump_lisp_Expression(simple_value(_node));
      printf(")");
      break;
    case KEYcomposite:
      printf("%c(composite",10);
dump_lisp_Expression(composite_initial(_node));
dump_lisp_Expression(composite_combiner(_node));
      printf(")");
      break;
    case KEYlattice:
      printf("%c(lattice",10);
dump_lisp_Expression(lattice_bottom(_node));
dump_lisp_Expression(lattice_join(_node));
dump_lisp_Expression(lattice_equal(_node));
      printf(")");
      break;
    case KEYno_default:
      printf("%c(no_default",10);
      printf(")");
      break;
  }
}

void dump_lisp_Units(Units _node){
  switch (Units_KEY(_node)) {
    default: fatal_error("dump_lisp_Units crashes");
    case KEYnil_Units:
      printf("%c(nil_Units",10);
      printf(")");
      break;
    case KEYlist_Units:
      printf("%c(list_Units",10);
dump_lisp_Unit(list_Units_elem(_node));
      printf(")");
      break;
    case KEYappend_Units:
      printf("%c(append_Units",10);
dump_lisp_Units(append_Units_l1(_node));
dump_lisp_Units(append_Units_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Declarations(Declarations _node){
  switch (Declarations_KEY(_node)) {
    default: fatal_error("dump_lisp_Declarations crashes");
    case KEYnil_Declarations:
      printf("%c(nil_Declarations",10);
      printf(")");
      break;
    case KEYlist_Declarations:
      printf("%c(list_Declarations",10);
dump_lisp_Declaration(list_Declarations_elem(_node));
      printf(")");
      break;
    case KEYappend_Declarations:
      printf("%c(append_Declarations",10);
dump_lisp_Declarations(append_Declarations_l1(_node));
dump_lisp_Declarations(append_Declarations_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Matches(Matches _node){
  switch (Matches_KEY(_node)) {
    default: fatal_error("dump_lisp_Matches crashes");
    case KEYnil_Matches:
      printf("%c(nil_Matches",10);
      printf(")");
      break;
    case KEYlist_Matches:
      printf("%c(list_Matches",10);
dump_lisp_Match(list_Matches_elem(_node));
      printf(")");
      break;
    case KEYappend_Matches:
      printf("%c(append_Matches",10);
dump_lisp_Matches(append_Matches_l1(_node));
dump_lisp_Matches(append_Matches_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Renamings(Renamings _node){
  switch (Renamings_KEY(_node)) {
    default: fatal_error("dump_lisp_Renamings crashes");
    case KEYnil_Renamings:
      printf("%c(nil_Renamings",10);
      printf(")");
      break;
    case KEYlist_Renamings:
      printf("%c(list_Renamings",10);
dump_lisp_Renaming(list_Renamings_elem(_node));
      printf(")");
      break;
    case KEYappend_Renamings:
      printf("%c(append_Renamings",10);
dump_lisp_Renamings(append_Renamings_l1(_node));
dump_lisp_Renamings(append_Renamings_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Signatures(Signatures _node){
  switch (Signatures_KEY(_node)) {
    default: fatal_error("dump_lisp_Signatures crashes");
    case KEYnil_Signatures:
      printf("%c(nil_Signatures",10);
      printf(")");
      break;
    case KEYlist_Signatures:
      printf("%c(list_Signatures",10);
dump_lisp_Signature(list_Signatures_elem(_node));
      printf(")");
      break;
    case KEYappend_Signatures:
      printf("%c(append_Signatures",10);
dump_lisp_Signatures(append_Signatures_l1(_node));
dump_lisp_Signatures(append_Signatures_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Types(Types _node){
  switch (Types_KEY(_node)) {
    default: fatal_error("dump_lisp_Types crashes");
    case KEYnil_Types:
      printf("%c(nil_Types",10);
      printf(")");
      break;
    case KEYlist_Types:
      printf("%c(list_Types",10);
dump_lisp_Type(list_Types_elem(_node));
      printf(")");
      break;
    case KEYappend_Types:
      printf("%c(append_Types",10);
dump_lisp_Types(append_Types_l1(_node));
dump_lisp_Types(append_Types_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Expressions(Expressions _node){
  switch (Expressions_KEY(_node)) {
    default: fatal_error("dump_lisp_Expressions crashes");
    case KEYnil_Expressions:
      printf("%c(nil_Expressions",10);
      printf(")");
      break;
    case KEYlist_Expressions:
      printf("%c(list_Expressions",10);
dump_lisp_Expression(list_Expressions_elem(_node));
      printf(")");
      break;
    case KEYappend_Expressions:
      printf("%c(append_Expressions",10);
dump_lisp_Expressions(append_Expressions_l1(_node));
dump_lisp_Expressions(append_Expressions_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Patterns(Patterns _node){
  switch (Patterns_KEY(_node)) {
    default: fatal_error("dump_lisp_Patterns crashes");
    case KEYnil_Patterns:
      printf("%c(nil_Patterns",10);
      printf(")");
      break;
    case KEYlist_Patterns:
      printf("%c(list_Patterns",10);
dump_lisp_Pattern(list_Patterns_elem(_node));
      printf(")");
      break;
    case KEYappend_Patterns:
      printf("%c(append_Patterns",10);
dump_lisp_Patterns(append_Patterns_l1(_node));
dump_lisp_Patterns(append_Patterns_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Formals(Formals _node){
  switch (Formals_KEY(_node)) {
    default: fatal_error("dump_lisp_Formals crashes");
    case KEYnil_Formals:
      printf("%c(nil_Formals",10);
      printf(")");
      break;
    case KEYlist_Formals:
      printf("%c(list_Formals",10);
dump_lisp_ValueDecl(list_Formals_elem(_node));
      printf(")");
      break;
    case KEYappend_Formals:
      printf("%c(append_Formals",10);
dump_lisp_Formals(append_Formals_l1(_node));
dump_lisp_Formals(append_Formals_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_TypeFormals(TypeFormals _node){
  switch (TypeFormals_KEY(_node)) {
    default: fatal_error("dump_lisp_TypeFormals crashes");
    case KEYnil_TypeFormals:
      printf("%c(nil_TypeFormals",10);
      printf(")");
      break;
    case KEYlist_TypeFormals:
      printf("%c(list_TypeFormals",10);
dump_lisp_TypeDecl(list_TypeFormals_elem(_node));
      printf(")");
      break;
    case KEYappend_TypeFormals:
      printf("%c(append_TypeFormals",10);
dump_lisp_TypeFormals(append_TypeFormals_l1(_node));
dump_lisp_TypeFormals(append_TypeFormals_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_Actuals(Actuals _node){
  switch (Actuals_KEY(_node)) {
    default: fatal_error("dump_lisp_Actuals crashes");
    case KEYnil_Actuals:
      printf("%c(nil_Actuals",10);
      printf(")");
      break;
    case KEYlist_Actuals:
      printf("%c(list_Actuals",10);
dump_lisp_Expression(list_Actuals_elem(_node));
      printf(")");
      break;
    case KEYappend_Actuals:
      printf("%c(append_Actuals",10);
dump_lisp_Actuals(append_Actuals_l1(_node));
dump_lisp_Actuals(append_Actuals_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_TypeActuals(TypeActuals _node){
  switch (TypeActuals_KEY(_node)) {
    default: fatal_error("dump_lisp_TypeActuals crashes");
    case KEYnil_TypeActuals:
      printf("%c(nil_TypeActuals",10);
      printf(")");
      break;
    case KEYlist_TypeActuals:
      printf("%c(list_TypeActuals",10);
dump_lisp_Type(list_TypeActuals_elem(_node));
      printf(")");
      break;
    case KEYappend_TypeActuals:
      printf("%c(append_TypeActuals",10);
dump_lisp_TypeActuals(append_TypeActuals_l1(_node));
dump_lisp_TypeActuals(append_TypeActuals_l2(_node));
      printf(")");
      break;
  }
}

void dump_lisp_PatternActuals(PatternActuals _node){
  switch (PatternActuals_KEY(_node)) {
    default: fatal_error("dump_lisp_PatternActuals crashes");
    case KEYnil_PatternActuals:
      printf("%c(nil_PatternActuals",10);
      printf(")");
      break;
    case KEYlist_PatternActuals:
      printf("%c(list_PatternActuals",10);
dump_lisp_Pattern(list_PatternActuals_elem(_node));
      printf(")");
      break;
    case KEYappend_PatternActuals:
      printf("%c(append_PatternActuals",10);
dump_lisp_PatternActuals(append_PatternActuals_l1(_node));
dump_lisp_PatternActuals(append_PatternActuals_l2(_node));
      printf(")");
      break;
  }
}

